In [1]:
import numpy as np

In [3]:
# 브로드캐스팅
nums = np.array([10,20,30,40])

In [5]:
nums2 = nums * 2 # 요소를 모두 2를 곱함. 새로운 객체로 만들어짐
print(nums)
print(nums2)

[10 20 30 40]
[20 40 60 80]


In [6]:
nums3 = nums - 5
print(nums3)

[ 5 15 25 35]


In [7]:
data = np.column_stack(([10,20,30], [1,2,3], [100, 200, 300]))
print(data)

[[ 10   1 100]
 [ 20   2 200]
 [ 30   3 300]]
