In [1]:
import numpy as np

In [2]:
nums = np.array([1,2,3,4])
print(nums)

[1 2 3 4]


In [5]:
nums2 = nums.reshape(2,2) # 2행 2열로 바꿈

print(nums2)

[[1 2]
 [3 4]]


In [8]:
nums3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(nums3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [18]:
nums4 = nums3.array(2,6)
print(nums4)

AttributeError: 'numpy.ndarray' object has no attribute 'array'